### ISSUE TITLE
Unit test case coverage for gs_service

### ISSUE THREAD

**Issue by kushal-mindgrep** [godspeedsystems/gs-node-service#1]
Test case scenarios for GS-Service:
- [x] 1. Invoking an event should execute the workflow
  - [x] 1 Request/ Response schema validation for events
- [x] 2. Failure (if below does not exist)
  - [x]     1. Function(within a function,  within an event)
  - [x]     2. Event
  - [x]     3. DataSource
- [x] 3. DataSource Schema Function Schema, Event schema validation (Json Schema for all YAML's using orderly)
- [x] 4. Framework functions
  - [x]     1. Parallel
  - [x]     2. Series
  - [x]     3. Combination
  - [x]     4. HTTP
  - [x]     5. Transform
  - [x]     6. Return
  - [x]     7. Switch
  - [x]     8. OnError
  - [x]     9.  Calling one YAML fn from another YAML fn
- [x] 5. GS-service src test cases.
- [x] Loading, functionality, fixtures

Note: Faker-Mockdata Generator >> Microservice testing
