### ISSUE TITLE
Integration of Frappe

### ISSUE THREAD

**Issue by kushal-mindgrep** [godspeedsystems/gs-node-service#167]
- [ ] Authentication
- [ ] Authorization
- [ ] Document Management
- [ ] Notifications (email, sms, pagerduty, slack, whatsapp)
- [ ] Rule Engine
- [ ] UI - Development
- [ ] UI - Workflow Management (Governance, maker checker, approver)
- [ ] UI - Analytics and Dashboards

Linked issues:- 
[ Card91 microservice] #653

**Comment by ashutoshmindgrep** [comment]
Admin UI for Documents and Access control
Managing the Access Control

It's a wrapper around S3(or any cloud based storage),
The whole API layer will be exposed by the Godspeed.

**Comment by siddarthvader** [comment]
starting with the basic POC of frappe framework to accomplish these tasks. 

- Create datamodels in frappe from UI.
- Read/write to database(using postgres since mac m1 have no support for mariadb@10.6 ) using frappe app
- generate crud API from the underneath postgres DB frappe app is writing to, need to see how this can be done since we are using prisma to generate crud API but i did not see anything in frappe saying they generate prisma model, but they do have their own ORM called virtual docs, we could probabbly write a loder on the top of it in godspeed to generate data models.
- Authn and Authz setup using frappe.
- Back office portal/ for our internal use case of account management. Since Frappe app provides another abstraction which lets us control the operations like writing to database using their own UI.


Largely Idea is here to generate data-models from frappe JSON based ORM which godspeed can consume as API, and have an UI to control the finer control of datasource, for example `blocking a user from getting more credit` or `extending spend limit of some people`
