### ISSUE TITLE
Import Godspeed projects as npm packages in other projects

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#351]
Objective: To import any Godspeed service as npm package. There are few assumptions which should be there in the Godspeed npm package:

1. The project directory structure in the npm package should be similar to the Godspeed service. For example, it should have directories like `src/`, `src/events`, `src/datasources`, `src/functions`, `src/mappings`, `src/plugins`, `config/`

To use datasources, events, functions as npm package.

- [x] [Import Godspeed project as npm package: Make plugins namespaced. Use underscore instead of dot notation for plugins loading.#509](https://github.com/godspeedsystems/gs-node-service/issues/509)
- [ ] [Import Godspeed project as npm package: Create copy_packages.js script to copy all the src/ directory of imported projects to current project#524](https://github.com/godspeedsystems/gs-node-service/issues/524)
- [ ] [Import Godspeed project as npm package: To install package.json of the imported project#523](https://github.com/godspeedsystems/gs-node-service/issues/523)
- [ ] Complete documentation of the feature.

**Comment by gurjotmindgrep** [comment]
[copy_packages.js.zip](https://github.com/godspeedsystems/gs-node-service/files/11934717/copy_packages.js.zip)

**Comment by ashutoshmindgrep** [comment]
Thanks @gurjotmindgrep :)
