### ISSUE TITLE
Migration of repo from mindgrep to Godspeed systems

### ISSUE THREAD

**Issue by arunsingh** [godspeedsystems/gs-node-service#501]
It will include migration :- 
- [x] github repo migration gs_service
- [x] dockerhub migration. 
- [x] github action updation. 
- [x] Migration of gs_service repo to godspeed systems: npm registry migration.
- [x] #525
- [x] #526
- [x] #527
- [ ] [Godspeed CLI Migration #33](https://github.com/godspeedsystems/godspeed-cli/issues/33)
