### ISSUE TITLE
Epic: Godspeed profiling and optimization

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#573]
- [x] [Do profiling of pino test with simple express app and godspeed app#574](https://github.com/godspeedsystems/gs-node-service/issues/574)
- [ ] [Move observability to background worker in gs-node-service#575](https://github.com/godspeedsystems/gs-node-service/issues/575)
- [ ] [Move logging to background worker in gs-node-service#576](https://github.com/godspeedsystems/gs-node-service/issues/576)

**Comment by arunsingh** [comment]
To be discussed with Kushal & have updates.
