### ISSUE TITLE
Epic: Axios Plugin Features

### ISSUE THREAD

**Issue by xCodeMuse** [godspeedsystems/gs-node-service#883]
### The problem
Axios has not only a gap between features of v1 and v2, but also can have more features as mentioned below. 

### The solution
- [x] Add support for Auth & Token refresh based on security schemes similar to V1 (https://docs.godspeed.systems/v1/microservices/authen-author)
- [x] Authentication system #944 
  - [x] token refresh from a custom auth function.
  - [x] The cutom auth function should Set the token automatically in the appropriate headers when making call to urls which require authentication
  - [x] Allow developer to specify status codes for refreshing token in an array. byd efault use 401.
  - [x] ensure only one token refresh call is made, concurrent api calls to wait for the response (this prevents request throttling to the authentications service)

- [x]  Setting headers in the datasource yaml will add those headers in every call to that datasource. 
- [x] Also implement the [axios retry functionality](https://github.com/godspeedsystems/gs-plugins/issues/141) 

### How we solve
Adapt the axios plugin and the CLI for the same

**Comment by mastersilv3r** [comment]
Need to confirm documentation.
